### PR TITLE
typecheck: Updating inferred type of initializer function

### PR DESCRIPTION
**Pull request by justinpark715**
Updating inferred type of initializer functions to be ForwardRef. Updating relevant test cases
Issue discovered while doing preliminary work in updating visit_call

### CODE REVIEW

**Comment by justinpark715** [comment]
Unsure if there was a specific reason you wanted the return type of initializers to be None @david-yz-liu ?

**Comment by david-yz-liu** [comment]
@justinpark715 the return type *is* `None`. Object creation in Python involves more than just calling `__init__`, although this is the simplification we normally use. You can read more about it in the Python Language Reference.

**Comment by justinpark715** [comment]
Right, in actual Python the return type is None, but within the TypeConstraints, is it okay to set the inferred type signature of the init function as Callable[[Foo], Foo] (or whatever class)?

**Comment by david-yz-liu** [comment]
I don't want to change the `__init__` signature to something that's not true in Python. There's room to emulate the correct behaviour with `__new__`, but I don't want you to spend time really looking into that right now.

**Pull request merged**
