### PR TITLE
Implement drawing control flow graphs to the pyta API

### PR DESCRIPTION
**Pull request by sushimon**
## Motivation and Context

Drawing CFGs is not actually a part of the pyta API so users wouldn't actually have access to this functionality. This PR aims to implement this functionality into the pyta API so users can now "visualize" the execution of their programs.

## Your Changes

**Description**:

- Slightly modified the code in `sample_usage/draw_cfg.py` so it can be a part of the `python_ta/cfg` submodule
- Created a new section in the pyta documentation to log this new feature
- Created new test cases to verify that this new feature properly creates the related `graphviz` files

**Type of change** (select all that apply):

- [x] New feature (non-breaking change which adds functionality)

## Testing

- Ran the new tests and verified that they all passed
- Ran the test suite locally and verified that they all passed
- Verified that CFGs were correctly being produced when called as per the API
- Generated the docs to verify that the new section was correctly added to the pyta documentation

## Questions and Comments (if applicable)

- Might just be a local bug but after generating the pyta docs and using the table of contents to navigate through each section, the newly added section occasionally disappears when clicking on other sections. I've attached some screenshots below:
image
image
Notice how the "Control Flow Graphs" section disappears once I click on "Loop Debugging"

- ~~I want to add some test cases but I'm not exactly sure how since it creates a new file.~~
- ~~I'm not sure if this was the correct move but I just copied the code directly from `sample_usage/draw_cfg.py` into the new file. I was originally going to import it but I'm pretty sure that the users won't have access to those files so duplicating the code here is fine.~~
- **FUTURE WORK:** create a new PR to update `sample_usage/draw_cfg.py` to have it use these new changes there.

## Checklist

- [x] I have performed a self-review of my own code.
- [x] I have verified that the CI tests have passed. 
- [x] I have reviewed the test coverage changes reported on Coveralls. 
- [x] I have added tests for my changes. 
- [x] I have updated the CHANGELOG.md file.

### CODE REVIEW

**Review by david-yz-liu — COMMENTED** [review]
@sushimon great! I didn't review your code, but in response to your comments/questions:

1. Not sure about the docs issue, I'll look into it but I wouldn't worry about it for now.
2. Testing is a bit tricky; since the point is to generate the files, why don't you look into using [snapshot testing](https://pypi.org/project/pytest-snapshot/) for this. Note: you can also use [tempfile](https://docs.python.org/3/library/tempfile.html) for the temporary graph output files.
3. Copying is correct, but you can go further: with this change, you should be able to import this code into `draw_cfg.py` and call it there, so that the code really isn't duplicated.

**Comment by sushimon** [comment]
Wait before merging as #901 might've messed up some of the testing. Coveralls is reporting a drastically lower code coverage.

**Review by david-yz-liu — COMMENTED** [review]
@sushimon good work, I left a more detailed review this time focused mainly on the documentation and API.

**Review by david-yz-liu — COMMENTED** [review]
@sushimon looks good, I just left two more comments.

I'm really not sure why the coverage is reported as going down by so much. It looks like the excluded folders aren't being properly excluded.

Can you please recreate this pull request on a fresh branch directly off of `upstream/master` (i.e., without any additional merge commits or anything).

**Comment by sushimon** [comment]
> @sushimon looks good, I just left two more comments.
> 
> I'm really not sure why the coverage is reported as going down by so much. It looks like the excluded folders aren't being properly excluded.
> 
> Can you please recreate this pull request on a fresh branch directly off of `upstream/master` (i.e., without any additional merge commits or anything).

Moved over to #904 as per the comment above.

**Pull request closed without merging**
