### PR TITLE
Make PlainReporter and ColorReporter display the time that the report was generated

### PR DESCRIPTION
**Pull request by MariaMa-GitHub**
## Motivation and Context

Currently, the `HTMLReporter` displays the time that the report was generated. However, the `PlainReporter` and the `ColorReporter` are lacking this feature. This pull request solves the issue by adding this feature to `PlainReporter` (and `ColorReporter` inherits from it).

## Your Changes

**Description**: I copied the date and time calculation from the `display_messages` method in the `HTMLReporter` and created a method in `PythonTaReporter` (parent class) from it. I then called this method in the `print_messages` method in `PlainReporter`, and since `ColorReporter` inherits from `PlainReporter`, it also gets this feature.

**Type of change** (select all that apply):

- [X] New feature (non-breaking change which adds functionality)

## Testing

This code has been successfully tested with the following tests:

```python
import python_ta
python_ta.check_all(config={"output-format": "python_ta.reporters.PlainReporter"})
```
```python
import python_ta
python_ta.check_all(config={"output-format": "python_ta.reporters.ColorReporter"})
```

## Checklist

- [X] I have performed a self-review of my own code.
- [X] I have verified that the CI tests have passed. 
- [X] I have reviewed the test coverage changes reported on Coveralls.

### CODE REVIEW

**Review by david-yz-liu — COMMENTED** [review]
@MariaMa-GitHub start by looking at the `.pylintrc` configuration file. Identify the key that controls the PythonTA reporter type, and then pass in an appropriate dictionary as the `config` parameter to `python_ta.check_all`

**Comment by MariaMa-GitHub** [comment]
> @MariaMa-GitHub start by looking at the `.pylintrc` configuration file. Identify the key that controls the PythonTA reporter type, and then pass in an appropriate dictionary as the `config` parameter to `python_ta.check_all`

Thank you, I was successfully able to run it and test my code.

**Comment by david-yz-liu** [comment]
@MariaMa-GitHub that's great. Please update your pull request description to clarify the testing status. It sounds like you encountered other issues when running the test suite on your code: follow up with me separately on Slack about this, and make sure to provide more information

**Review by david-yz-liu — COMMENTED** [review]
@MariaMa-GitHub great work. I'm happy with the current format of the datetime in the output report A few comments:

1. Since this is a user-facing change, you should add an entry to the CHANGELOG under a new `[enhancements]` subsection (under `[unreleased]`)
2. As you brought up in yesterday's meeting, it would be good to pull out the code for generating the datetime string into a `PythonTaReporter` method, so that it can be shared across the plain/colour/html reporters.

**Comment by MariaMa-GitHub** [comment]
@david-yz-liu I have two questions regarding this pull request:

1. Why is Eleonora's changes appearing in my "Files changes" (more specifically, the python_ta/checkers/pycodestyle_checker.py file)? I am pretty sure I only pulled the changes and did nothing else.
2. Do I have to create a separate pull request to change how datetime display works for `HTMLReporter`? I created a `_generate_report_date_time` method in `PythonTaReporter` but I left `HTMLReporter` as is and only made `PlainReporter` and `ColorReporter` use it. Should I modify the existing `HTMLReporter` code to use this new method as well?

**Comment by david-yz-liu** [comment]
@MariaMa-GitHub 

1. I'm not sure how you tried to update your branch, but your commit history suggests that you did not do it correctly. The _only_ thing you should be doing to update your branch is `git pull upstream master`. You can try to do this now. If that doesn't work, send me an exact screenshot of the terminal input and output via Slack.
2. You can modify `HTMLReporter` in this pull request.

**Review by david-yz-liu — APPROVED** [review]

**Pull request merged**
